##############################
# Language Translation EN
##############################

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name       = "So Home"
    url        = "/"
    weight     = 1

  [[languages.en.menu.main]]
    identifier = "what-is-dogecoin"
    name       = "What is Dogecoin?"
    url        = "#what-is-dogecoin"
    weight     = 2

  [[languages.en.menu.main]]
    identifier = "wallets"
    name       = "Much Wallets"
    url        = "#wallets"
    weight     = 3

  [[languages.en.menu.main]]
    identifier = "community"
    name       = "Very Community"
    url        = "#community"
    weight     = 4

  [[languages.en.menu.main]]
    identifier = "dogepedia"
    name       = "So Dogepedia"
    url        = "dogepedia/"
    weight     = 5

    [languages.en.menu.main.params]
      class = "parent"

    [[languages.en.menu.main]]
    identifier = "faq"
    name       = "FAQ"
    url        = "dogepedia/#faq"
    parent = "dogepedia"
    weight     = 5

    [[languages.en.menu.main]]
    identifier = "how-tos"
    name       = "How Tos"
    url        = "dogepedia/#howto"
    parent = "dogepedia"
    weight     = 5

    [[languages.en.menu.main]]
    identifier = "documentation"
    name       = "Documentation"
    url        = "dogepedia/#documentation"
    parent = "dogepedia"
    weight     = 5

    [[languages.en.menu.main]]
    identifier = "resource"
    name       = "Resources"
    url        = "resources/"
    parent = "dogepedia"
    weight     = 5

#[[languages.en.params.footerLegal]]
#    name = "Terms & Conditions"
#    url  = "/terms"

#  [[languages.en.params.footerLegal]]
#    name = "Privacy Policy"
#    url  = "/legal"

  [[languages.en.params.footerLegal]]
    name = "Trademarks"
    url  = "/trademarks"

[[languages.en.params.footerFoundation]]
    name = "About"
    url  = "https://foundation.dogecoin.com/about/"

  [[languages.en.params.footerFoundation]]
    name = "Manifesto"
    url  = "https://foundation.dogecoin.com/manifesto/"

  [[languages.en.params.footerFoundation]]
    name = "Advisors"
    url  = "https://foundation.dogecoin.com/about/"

  [[languages.en.params.footerFoundation]]
    name = "Blog"
    url  = "https://foundation.dogecoin.com/announcements/"

  [[languages.en.params.footerFoundation]]
    name = "Trailmap"
    url  = "https://foundation.dogecoin.com/trailmap/prologue/"